include: package:lint/analysis_options.yaml

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    public_member_api_docs: ignore  # ✅ Ignore missing documentation warnings
    avoid_classes_with_only_static_members: ignore  # ✅ Ignore static-only class warnings
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"

linter:
  rules:
    - prefer_const_constructors
    - prefer_final_locals
    - avoid_print
    - prefer_single_quotes
    - always_use_package_imports
    # - prefer_relative_imports  # ❌ Removed (conflict)
    - unnecessary_this
    - avoid_empty_else
    - prefer_typing_uninitialized_variables
    - avoid_void_async
    - unnecessary_late
    - sort_constructors_first
    - require_trailing_commas
    - directives_ordering
    - sort_pub_dependencies