name: fotosfera
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies: 

  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  easy_localization_generator: ^0.3.3
  equatable: ^2.0.7
  firebase_analytics: ^11.4.4
  firebase_core: ^3.12.1
  firebase_crashlytics: ^4.3.4
  firebase_messaging: ^15.2.4
  firebase_performance: ^0.10.1+4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  intl: ^0.19.0
  logger: ^2.5.0
  mockito: ^5.4.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  # dart_code_metrics removed

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

dependency_overrides:
  file: ^7.0.0