// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmedGS_BkjeYY3OVUD4o-63rC_6U8-E30',
    appId: '1:704396553547:web:32f6ac1b4a4784b128ccce',
    messagingSenderId: '704396553547',
    projectId: 'fotosfera-23f52',
    authDomain: 'fotosfera-23f52.firebaseapp.com',
    storageBucket: 'fotosfera-23f52.firebasestorage.app',
    measurementId: 'G-K074Y40WHX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnpwQlT74cktnULkBBon8-CvRnoWV67I8',
    appId: '1:704396553547:android:ac2c9f1d0a5d1c8328ccce',
    messagingSenderId: '704396553547',
    projectId: 'fotosfera-23f52',
    storageBucket: 'fotosfera-23f52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0hlt5v3OrhuXpf_QW2Vd965ccfu-W5rQ',
    appId: '1:704396553547:ios:7c9542566e0212c128ccce',
    messagingSenderId: '704396553547',
    projectId: 'fotosfera-23f52',
    storageBucket: 'fotosfera-23f52.firebasestorage.app',
    iosBundleId: 'com.example.fotosfera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0hlt5v3OrhuXpf_QW2Vd965ccfu-W5rQ',
    appId: '1:704396553547:ios:7c9542566e0212c128ccce',
    messagingSenderId: '704396553547',
    projectId: 'fotosfera-23f52',
    storageBucket: 'fotosfera-23f52.firebasestorage.app',
    iosBundleId: 'com.example.fotosfera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmedGS_BkjeYY3OVUD4o-63rC_6U8-E30',
    appId: '1:704396553547:web:34f81d17b7ca932e28ccce',
    messagingSenderId: '704396553547',
    projectId: 'fotosfera-23f52',
    authDomain: 'fotosfera-23f52.firebaseapp.com',
    storageBucket: 'fotosfera-23f52.firebasestorage.app',
    measurementId: 'G-MX6CEJL3H7',
  );
}
